name: deployment to production server

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: update chat bot
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/github-actions/chat_bot
            git pull origin master
            rm -rf .env
            cat << WRITEDATA >> .env
            BOT_TOKEN = "${{ secrets.ENV_BOT_TOKEN }}"
            DB_URL = "${{ secrets.ENV_DB_URL }}"
            WRITEDATA
            docker-compose up -d --build
